### ISSUE TITLE
Cannot install package?

### ISSUE THREAD

**Issue by Mon-ius** [LJaraCastillo/flutter_sensors#1]
Hi, why flutter show there is no such package in their storage? Have you already uploadde it ?

**Comment by LJaraCastillo** [comment]
I haven't uploaded to pub.dartlang.org yet. I need to make some test to the iOS part of the code but i have been busy. Once i finish testing i will publish it so you could install it like other packages. As a temporary solution you can install it from git copying this in your pubspec.yaml

```
dependencies:
  flutter_sensors:
    git:
      url: https://github.com/LJaraCastillo/flutter_sensors.git
```
